name: enrichm
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - diamond
  - hmmer >=3.4,<4
  - parallel
  - prodigal
  - mmseqs2
  - mcl
  - python 3.*
  - certifi >=2024
  - python-dateutil >=2.9.0.post0,<3
  - statsmodels >=0.14.5,<0.15
  - numpy >=2.3.2,<3
  - pandas >=2.3.2,<3
  - scipy >=1.16.1,<2
  - biopython >=1.85,<2
  - fuzzywuzzy >=0.18.0,<0.19
  - six >=1.17.0,<2
  - scikit-learn >=1.7.1,<2
  - decorator >=5.2.1,<6
  - r >=4.4,<4.5
  - pyarrow >=21.0.0,<22
  - dendropy >=5.0.8,<6
  - matplotlib >=3.10.8,<4
  - pandas >=2.3.2,<3
  - pip
  - pip:
    - pyrodigal>=3.6.3.post1,<4
    - polars>=1.32.3,<2
