[workspace]
authors = ["Joel <joel.anthonyb@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "enrichM"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
diamond = "*"
hmmer = ">=3.4,<4"
parallel = "*"
prodigal = "*"
mmseqs2 = "*"
python = "3.*"
python-dateutil = ">=2.9.0.post0,<3"
statsmodels = ">=0.14.5,<0.15"
numpy = ">=2.3.2,<3"
pandas = ">=2.3.2,<3"
scipy = ">=1.16.1,<2"
biopython = ">=1.85,<2"
fuzzywuzzy = ">=0.18.0,<0.19"
six = ">=1.17.0,<2"
scikit-learn = ">=1.7.1,<2"
decorator = ">=5.2.1,<6"
pytest = ">=8.4.1,<9"
r = ">=4.4,<4.5"
pyarrow = ">=21.0.0,<22"

[pypi-dependencies]
pyrodigal = ">=3.6.3.post1, <4"
ipython = ">=9.4.0, <10"
polars = ">=1.32.3, <2"
